<a href="https://colab.research.google.com/github/MiguelRR2029/THC_MiguelR/blob/main/Clase_19_10_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)




0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])

6


In [ ]:
l = ([1, 2, 3], [4, 5, 6], [7, 8, 9])
suma=0
for i in range(len(l)):
  for j in range(len(l)):
    suma=suma+l[i][j]
print(suma)

45


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
suma=0
for i in range(len(arr)):
  for j in range(len(arr)):
    suma=suma+arr[i,j]
print(suma)

45


In [ ]:
l = ([1, 1, 1], [1, 1, 1], [1, 1, 1])
L = ([1, 1, 1], [1, 1, 1], [1, 1, 1])
prod=1
suma=0
n=len(l)
C=n*[[0.0, 0.0, 0.0]]
for i in range(len(l)):
  for j in range(len(l)):
    C[i][j]=l[i][j]*L[i][j]
  suma=suma+C[i][j]
  print(suma)

1
2
3


In [ ]:

def prodpunto(a,b):
  pp=0
  for i in range (len(a)):
    pp=pp+a[i]*b[i]
  return pp


In [ ]:
arr2 = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
arr3 = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
Pp_por_reng=np.array([0,0,0])
Pp_por_col=np.array([0,0,0])


In [ ]:
for i in range(len(arr2)):
  Pp_por_reng[i]=prodpunto(arr2[i],arr3[i])

Pp_por_reng

array([3, 3, 3])

In [ ]:
def AC(a,col):
  nuevo=[]
  for i in range(len(a)):
    nuevo.append(a[i,col])

  return np.array(nuevo)

In [ ]:
coll=AC(arr2,0)
coll

array([1, 1, 1])

In [ ]:
for i in range(len(arr2)):
  Pp_por_col[i]=prodpunto(AC(arr2,i),AC(arr3,i))

Pp_por_col

array([3, 3, 3])